/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/aboutModel-transformed.glb')
  const { actions } = useAnimations(animations, group)

  //used to play animation
  useEffect(() => {
    actions.Action.play()
    actions.dogTail.play()
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 7.01, 9]} rotation={[0, -Math.PI / 2, 0]}>
        <primitive object={nodes.Bone} />
        <skinnedMesh
          geometry={nodes['13648_Polo_Pants_v2_L3'].geometry}
          material={materials['13648PoloPants_button']}
          skeleton={nodes['13648_Polo_Pants_v2_L3'].skeleton}
        />
        <skinnedMesh
          geometry={nodes['13648_Polo_Pants_v2_L3_1'].geometry}
          material={materials['13648PoloPants_cloth']}
          skeleton={nodes['13648_Polo_Pants_v2_L3_1'].skeleton}
        />
        <skinnedMesh
          geometry={nodes['13648_Polo_Pants_v2_L3_2'].geometry}
          material={nodes['13648_Polo_Pants_v2_L3_2'].material}
          skeleton={nodes['13648_Polo_Pants_v2_L3_2'].skeleton}
        />
        <skinnedMesh
          geometry={nodes['13648_Polo_Pants_v2_L3_3'].geometry}
          material={materials.MOUTH}
          skeleton={nodes['13648_Polo_Pants_v2_L3_3'].skeleton}
        />
        <skinnedMesh
          geometry={nodes['13648_Polo_Pants_v2_L3_4'].geometry}
          material={materials.Mat_1}
          skeleton={nodes['13648_Polo_Pants_v2_L3_4'].skeleton}
        />
        <skinnedMesh
          geometry={nodes['13648_Polo_Pants_v2_L3_5'].geometry}
          material={materials['Material.002']}
          skeleton={nodes['13648_Polo_Pants_v2_L3_5'].skeleton}
        />
        <skinnedMesh
          geometry={nodes['13648_Polo_Pants_v2_L3_6'].geometry}
          material={materials.EYES}
          skeleton={nodes['13648_Polo_Pants_v2_L3_6'].skeleton}
        />
        <skinnedMesh
          geometry={nodes['13648_Polo_Pants_v2_L3_7'].geometry}
          material={materials['1A1A1A.002']}
          skeleton={nodes['13648_Polo_Pants_v2_L3_7'].skeleton}
        />
        <skinnedMesh
          geometry={nodes['13648_Polo_Pants_v2_L3_8'].geometry}
          material={materials['FFFFFF.002']}
          skeleton={nodes['13648_Polo_Pants_v2_L3_8'].skeleton}
        />
      </group>
      <group name="dog" position={[15.61, 2.92, 9.81]} rotation={[0, 0, -2.58]} scale={0.73}>
        <primitive object={nodes.Bone_1} />
        <primitive object={nodes.Bone003} />
        <skinnedMesh
          geometry={nodes.Geo_Puppy.geometry}
          material={materials.lambert2SG}
          skeleton={nodes.Geo_Puppy.skeleton}
        />
      </group>
      <mesh
        geometry={nodes.Sphere_Ground.geometry}
        material={nodes.Sphere_Ground.material}
        position={[0.02, 0.17, -6.81]}
        scale={[32.08, 0.08, 32.08]}
      />
      <mesh
        geometry={nodes.dumbell.geometry}
        material={materials.phong1SG}
        position={[-25.7, 1.21, 2.42]}
        scale={10.08}
      />
      <group position={[-15.88, 2.04, 9.71]} rotation={[-Math.PI / 2, 0, 0.77]} scale={[201.31, 201.31, 201.31]}>
        <mesh geometry={nodes.Barbell_1.geometry} material={materials.Barbell_Weights} />
        <mesh geometry={nodes.Barbell_2.geometry} material={materials.Barbell_Bar} />
        <mesh geometry={nodes.Barbell_3.geometry} material={materials.Barbell_Collar} />
      </group>
      <mesh
        geometry={nodes.Xbox_Controller.geometry}
        material={materials.Mat}
        position={[8.22, 0, 1.71]}
        rotation={[0, 0.48, 0]}
        scale={0.09}
      />
      <group position={[0.53, 13.08, -16.56]} scale={[18.97, 11.69, 11.69]}>
        <mesh geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials._crayfishdiffuse} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials['02___Default']} />
        <mesh geometry={nodes.Cube005_3.geometry} material={nodes.Cube005_3.material} />
        <mesh geometry={nodes.Cube005_4.geometry} material={materials['07___Default']} />
      </group>
    </group>
  )
}

useGLTF.preload('/aboutModel-transformed.glb')
