/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/fb-transformed.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh 
        geometry={nodes.Cube.geometry}
        material={materials['Material.001']}
        position={[0.48, 3.64, 1.6]}
        scale={0.39}
      />
      <mesh geometry={nodes.Sphere.geometry} material={materials.Material} position={[0, 2.73, 0]} scale={1.96} />
    </group>
  )
}

useGLTF.preload('/fb-transformed.glb')
