/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/gmail-transformed.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials['Material.001']}
        position={[-4.46, 2.73, 0]}
        scale={1.96}
      />
      <group position={[-4.46, 2.65, 1.76]} scale={[-0.42, 0.34, 0.42]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cube003_3.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube003_4.geometry} material={materials['Material.004']} />
      </group>
    </group>
  )
}

useGLTF.preload('/gmail-transformed.glb')
